name: Deploy Portfolio in GitHub Pages

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Deploy Angular app to prod
        run: npm run build -- --configuration production --output-path=dist --base-href=/Portfolio/

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_ACTION }}
        run: |
          npx angular-cli-ghpages --dir=dist --repo=https://github.com/AntonioPortada/Portfolio --name=${{ secrets.USER_NAME }} --email=${{ secrets.USER_EMAIL }} --branch=gh-pages --no-silent