name: Deploy Portfolio in GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Debug List files before and after build
        run: |
          echo "Before build:"
          ls -la
          npm run build
          echo "After build:"
          ls -la
          echo "Inside docs folder:"
          ls -la docs
          echo "Inside browser folder:"
          ls -la docs/browser
      
      - name: Move index.html to docs folder
        run: |
          mv docs/browser/index.html docs/index.html
          ls -la docs

      - name: Debug Check build output
        run: |
            echo "Listing contents of the workspace:"
            ls -la /home/runner/work/Portfolio/Portfolio
            echo "Listing contents of the docs folder:"
            ls -la /home/runner/work/Portfolio/Portfolio/docs


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.SECRET_ACTION }}
          publish_dir: ./docs
          # This workflow is triggered on push events to the master branch
