name: Deploy Portfolio in GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          npm install
          echo "Raiz"
          ls -la 
          echo "docs folder"
          ls -la docs

      - name: Build Angular app to prod
        working-directory: Portfolio
        run: |
          echo "before build"
          ls -la
          ls -la Portfolio
          ls -la Portfolio/docs
          npm run build:prod
          echo "after build"
          ls -la
          ls -la Portfolio
          ls -la Portfolio/docs

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: Portfolio/docs/browser
          branch: master
          token: ${{ secrets.SECRET_ACTION }}
